GET http://localhost:8080/subscribers/
###
GET http://localhost:8080/subscribers/5e07a1b09d7f92238ce276ad
###
POST http://localhost:8080/subscribers
content-Type: application/json

{
    "name": "Test",
    "subscribedToChannel": "BrandonBailey"
}
###
DELETE http://localhost:8080/subscribers/5e07a1b09d7f92238ce276ad