GET http://localhost:8080/subscribers/
###
GET http://localhost:8080/subscribers/5e079f448fac6735189c2079
###
POST http://localhost:8080/subscribers
content-Type: application/json

{
    "name": "Test",
    "subscribedToChannel": "BrandonBailey"
}
###
DELETE http://localhost:8080/subscribers/5e079f448fac6735189c2079